version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: ./app
    container_name: backend-app
    env_file:
      - .env
    depends_on:
      - db

  web:
    build: ./web
    container_name: nginx-web
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  db_data: